/* Immutable legacy-texture capture, Vulkan residency, and sampler ownership. */
#pragma once

#include "vk_frame.h"
#include "vk_renderer_runtime.h"
#include "vk_state_tracker.h"
#include "../core/render_device_contract.h"

#include <stddef.h>
#include <stdint.h>
#include <memory>
#include <vector>

namespace piccu
{
namespace render
{
namespace vk
{

// Large, one-shot texture transfers must not permanently inflate every frame
// context's mapped upload arena. They use a timeline-retired staging buffer.
constexpr VkDeviceSize kDedicatedTextureUploadThreshold = 16u * 1024u * 1024u;

struct TextureResidencyConfig
{
	// Zero disables automatic byte-budget eviction. Explicit eviction and cache
	// invalidation remain available.
	VkDeviceSize resident_byte_budget = 0;
	uint32_t maximum_font_layers = 256;
};

struct TextureResidencyStats
{
	uint64_t logical_versions = 0;
	uint64_t uploads = 0;
	uint64_t upload_bytes = 0;
	uint64_t resident_images = 0;
	uint64_t resident_bytes = 0;
	uint64_t recycled_images = 0;
	uint64_t evicted_images = 0;
};

struct ResidentTexture
{
	TextureVersionId id = kInvalidId;
	VkImage image = VK_NULL_HANDLE;
	VkImageView view = VK_NULL_HANDLE;
	VkFormat format = VK_FORMAT_UNDEFINED;
	VkExtent3D extent = {};
	uint32_t mip_count = 0;
	uint32_t array_texture = 0;
	uint64_t last_use_timeline = 0;

	bool Valid() const noexcept
	{
		return id != kInvalidId && image != VK_NULL_HANDLE &&
			view != VK_NULL_HANDLE;
	}
};

// Converts one legacy CPU texel to the byte-for-byte RGBA8 value generated by
// GL4's unpack translation tables. Transparent 1555 texels become (0,0,0,0).
void ConvertLegacy1555ToRgba8(uint16_t source, uint8_t output[4]) noexcept;
void ConvertLegacy4444ToRgba8(uint16_t source, uint8_t output[4]) noexcept;

class TextureManager final
{
public:
	TextureManager();
	~TextureManager();

	TextureManager(const TextureManager &) = delete;
	TextureManager &operator=(const TextureManager &) = delete;

	bool Initialize(Platform *platform, ResourceAllocator *allocator,
		FrameScheduler *frames, ResourceStateTracker *state_tracker,
		const TextureResidencyConfig &config = TextureResidencyConfig());
	void Shutdown(bool device_lost = false) noexcept;
	bool Ready() const noexcept { return ready_; }

	// Resolve performs the normative capture-time CPU snapshot. The returned
	// upload payload is owned by capture and is therefore immutable.
	bool Resolve(const TextureRequest &request, RenderCaptureSegment *capture,
		ResolvedTexture *resolved);
	bool ResolveTerrainArrays(const TerrainArrayRequest &request,
		RenderCaptureSegment *capture, ResolvedTexture *base,
		ResolvedTexture *lightmap);

	// Records the upload for a captured version into the current frame command
	// buffer. Repeated calls for an already-resident version are no-ops.
	bool EnsureResident(const CapturedTextureVersion &captured,
		const RenderCaptureSegment &capture, ResidentTexture *resident = nullptr);
	bool GetResident(TextureVersionId id, ResidentTexture *resident) const;

	// Pin after submission. Invalidation never destroys a pinned image early;
	// ResourceAllocator's timeline death row owns physical destruction.
	bool Pin(TextureVersionId id, uint64_t submission_timeline);
	bool PinCapture(const RenderCaptureSegment &capture,
		uint64_t submission_timeline);
	void DiscardCapture(const RenderCaptureSegment &capture);
	void Collect(uint64_t completed_timeline);
	VkDeviceSize Evict(VkDeviceSize bytes_to_free,
		uint64_t completed_timeline);
	void Invalidate(TextureMappingInvalidationReason reason,
		uint64_t completed_timeline);
	bool ReleaseLogicalHandle(int32_t logical_handle, uint32_t map_type,
		uint64_t completed_timeline);

	VkSampler Sampler(SamplerSemantic semantic) const noexcept;
	VkSampler WorldSampler(uint32_t index) const noexcept;
	SamplerSemantic SelectSampler(const TextureRequest &request) const noexcept;
	uint32_t SelectWorldSamplerIndex(const TextureRequest &request,
		bool array_texture) const noexcept;

	const TextureResidencyStats &Stats() const noexcept { return stats_; }
	TextureVersionId Diagnostic2D() const noexcept { return diagnostic_2d_; }
	TextureVersionId DiagnosticArray() const noexcept { return diagnostic_array_; }

private:
	struct LegacyIdentity
	{
		uintptr_t data = 0;
		uint32_t width = 0;
		uint32_t height = 0;
		uint32_t storage_width = 0;
		uint32_t mip_count = 0;
		uint32_t format = 0;
		uint32_t used = 0;
		int32_t cache_cookie = -1;
	};

	struct LogicalMapping
	{
		TextureVersionId version = kInvalidId;
		LegacyIdentity identity;
		uint32_t generation = 0;
	};

	struct Version
	{
		CapturedTextureVersion captured = {};
		AllocatedImage allocation;
		std::shared_ptr<const std::vector<uint8_t>> cpu_snapshot;
		TextureVersionId recycle_candidate = kInvalidId;
		VkDeviceSize byte_size = 0;
		uint32_t array_texture = 0;
		uint32_t diagnostic = 0;
		uint32_t current_mapping = 0;
		uint64_t pending_upload_capture_key = 0;
		uint64_t last_resolve_serial = 0;
		std::vector<uint64_t> pending_capture_keys;
	};

	struct FontLayer
	{
		int32_t handle = -1;
		LegacyIdentity identity;
		uint32_t generation = 0;
	};

	struct FontArray
	{
		uint32_t width = 0;
		uint32_t height = 0;
		uint32_t generation = 0;
		TextureVersionId version = kInvalidId;
		std::vector<FontLayer> layers;
		std::vector<uint8_t> rgba;
	};

	struct TerrainArraySource
	{
		int32_t handle = -1;
		LegacyIdentity identity;
	};

	struct PendingStaging
	{
		uint64_t capture_key = 0;
		AllocatedBuffer buffer;
	};

	Version *FindVersion(TextureVersionId id);
	const Version *FindVersion(TextureVersionId id) const;
	bool ResolveDiagnostic(bool array_texture, RenderCaptureSegment *capture,
		ResolvedTexture *resolved);
	bool ResolveBitmap(const TextureRequest &request, RenderCaptureSegment *capture,
		ResolvedTexture *resolved);
	bool ResolveLightmap(const TextureRequest &request, RenderCaptureSegment *capture,
		ResolvedTexture *resolved);
	bool ResolveFont(const TextureRequest &request, RenderCaptureSegment *capture,
		ResolvedTexture *resolved);
	bool EmitCapturedVersion(Version *version, RenderCaptureSegment *capture,
		CapturedTextureVersion *captured);
	Version *CreateVersion(uint32_t width, uint32_t height, uint32_t layers,
		uint32_t mip_count, uint32_t generation, bool array_texture,
		bool diagnostic, std::vector<uint8_t> &&snapshot,
		TextureVersionId recycle_candidate);
	bool ObserveBitmap(int32_t handle, LegacyIdentity *identity,
		uint32_t *dirty_flags) const;
	bool ObserveLightmap(int32_t handle, LegacyIdentity *identity,
		uint32_t *dirty_flags, float uv_scale[2]) const;
	bool SnapshotBitmap(int32_t handle, LegacyIdentity *identity,
		std::vector<uint8_t> *rgba, uint32_t *dirty_flags) const;
	bool SnapshotLightmap(int32_t handle, LegacyIdentity *identity,
		std::vector<uint8_t> *rgba, uint32_t *dirty_flags,
		float uv_scale[2]) const;
	bool SnapshotFontLayer(int32_t handle, LegacyIdentity *identity,
		std::vector<uint8_t> *rgba, uint32_t *dirty_flags) const;
	bool CreateSamplers();
	void DestroySamplers() noexcept;
	void RetireVersion(Version *version, uint64_t completed_timeline);
	void ClearCurrentMapping(TextureVersionId id);
	void InvalidateMappingsTo(TextureVersionId id);
	bool IsReferenced(const RenderCaptureSegment &capture,
		TextureVersionId id) const;
	static bool IdentityEqual(const LegacyIdentity &left,
		const LegacyIdentity &right) noexcept;
	static bool TerrainIdentityEqual(const LegacyIdentity &left,
		const LegacyIdentity &right) noexcept;
	static VkDeviceSize TextureBytes(uint32_t width, uint32_t height,
		uint32_t layers, uint32_t mip_count) noexcept;
	static uint64_t CaptureKey(const RenderCaptureSegment &capture) noexcept;
	void RetireCaptureStaging(uint64_t capture_key, uint64_t timeline);

	Platform *platform_;
	ResourceAllocator *allocator_;
	FrameScheduler *frames_;
	ResourceStateTracker *state_tracker_;
	TextureResidencyConfig config_;
	std::vector<LogicalMapping> bitmap_mappings_;
	std::vector<LogicalMapping> lightmap_mappings_;
	std::vector<Version> versions_;
	std::vector<PendingStaging> pending_staging_;
	FontArray font_array_;
	TextureVersionId terrain_base_version_;
	TextureVersionId terrain_lightmap_version_;
	uint64_t terrain_base_signature_;
	uint64_t terrain_lightmap_signature_;
	uint32_t terrain_array_generation_;
	std::vector<TerrainArraySource> terrain_base_sources_;
	TerrainArraySource terrain_lightmap_sources_[4];
	bool terrain_sources_valid_;
	VkSampler samplers_[static_cast<uint32_t>(SamplerSemantic::Count)];
	VkSampler world_samplers_[kWorldSamplerCount];
	TextureVersionId diagnostic_2d_;
	TextureVersionId diagnostic_array_;
	uint64_t next_content_serial_;
	uint64_t resolve_serial_;
	TextureResidencyStats stats_;
	bool ready_;
};

} // namespace vk
} // namespace render
} // namespace piccu
