if(NOT DEFINED OUTPUT OR NOT DEFINED LAN_CONNECTOR OR NOT DEFINED TRACKER_CONNECTOR)
	message(FATAL_ERROR "Missing built-in connector resource arguments")
endif()

file(TO_CMAKE_PATH "${LAN_CONNECTOR}" LAN_CONNECTOR_RC)
file(TO_CMAKE_PATH "${TRACKER_CONNECTOR}" TRACKER_CONNECTOR_RC)
file(WRITE "${OUTPUT}"
"#include \"builtin_connectors.h\"\n"
"IDR_BUILTIN_DIRECT_TCPIP RCDATA \"${LAN_CONNECTOR_RC}\"\n"
"IDR_BUILTIN_TRACKER RCDATA \"${TRACKER_CONNECTOR_RC}\"\n")
